In [1]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/taylor/.local/lib/python3.10/site-packages (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/taylor/.local/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/lib/python3/dist-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
# Get argus flows from PCAPs
!../util/process_data_argus.sh

ra[822432]: 09:35:55.383802 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822456]: 09:35:56.407788 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822470]: 09:35:58.428111 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
../util/process_data_argus.sh: line 3: 822476 Segmentation fault      (core dumped) ra -r $filename.argus -c',' -s srcid rank stime ltime trans flgs seq dur runtime idle mean stddev sum min max smac dmac soui doui saddr daddr proto sport dport stos dtos sdsb ddsb sco dco sttl dttl shops dhops sipid dipid smpls dmpls autoid sas das ias cause nstroke snstroke dnstroke pkts spkts dpkts bytes sbytes dbytes appbytes sappbytes dappbytes pcr load sload dload loss sloss dloss ploss psloss pdloss retrans sretrans dretrans pretrans psretrans pdretrans sgap dgap rate srate drate dir sintpkt sintdist sintpktact sintdistact sintpktidl sintdistidl dintpkt dintdist dintpktact dintdistact dintpktidl dintdistidl sjit sjitact sjitidle djit djitact djitidle state label suser duser swin dwin svlan dvlan svid dvid svpri dvpri srng erng stcpb dtcpb tcprtt synack ackdat tcpopt inode offset smeansz dmeansz spktsz smaxsz dpktsz dmaxsz sminsz dminsz dminsz > $filename.csv
ra[822496]: 09:36:01.694771 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
../util/process_data_argus.sh: line 3: 822508 Segmentation fault      (core dumped) ra -r $filename.argus -c',' -s srcid rank stime ltime trans flgs seq dur runtime idle mean stddev sum min max smac dmac soui doui saddr daddr proto sport dport stos dtos sdsb ddsb sco dco sttl dttl shops dhops sipid dipid smpls dmpls autoid sas das ias cause nstroke snstroke dnstroke pkts spkts dpkts bytes sbytes dbytes appbytes sappbytes dappbytes pcr load sload dload loss sloss dloss ploss psloss pdloss retrans sretrans dretrans pretrans psretrans pdretrans sgap dgap rate srate drate dir sintpkt sintdist sintpktact sintdistact sintpktidl sintdistidl dintpkt dintdist dintpktact dintdistact dintpktidl dintdistidl sjit sjitact sjitidle djit djitact djitidle state label suser duser swin dwin svlan dvlan svid dvid svpri dvpri srng erng stcpb dtcpb tcprtt synack ackdat tcpopt inode offset smeansz dmeansz spktsz smaxsz dpktsz dmaxsz sminsz dminsz dminsz > $filename.csv
ra[822521]: 09:36:05.802422 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
../util/process_data_argus.sh: line 3: 822528 Segmentation fault      (core dumped) ra -r $filename.argus -c',' -s srcid rank stime ltime trans flgs seq dur runtime idle mean stddev sum min max smac dmac soui doui saddr daddr proto sport dport stos dtos sdsb ddsb sco dco sttl dttl shops dhops sipid dipid smpls dmpls autoid sas das ias cause nstroke snstroke dnstroke pkts spkts dpkts bytes sbytes dbytes appbytes sappbytes dappbytes pcr load sload dload loss sloss dloss ploss psloss pdloss retrans sretrans dretrans pretrans psretrans pdretrans sgap dgap rate srate drate dir sintpkt sintdist sintpktact sintdistact sintpktidl sintdistidl dintpkt dintdist dintpktact dintdistact dintpktidl dintdistidl sjit sjitact sjitidle djit djitact djitidle state label suser duser swin dwin svlan dvlan svid dvid svpri dvpri srng erng stcpb dtcpb tcprtt synack ackdat tcpopt inode offset smeansz dmeansz spktsz smaxsz dpktsz dmaxsz sminsz dminsz dminsz > $filename.csv
../util/process_data_argus.sh: line 3: 822540 Segmentation fault      (core dumped) ra -r $filename.argus -c',' -s srcid rank stime ltime trans flgs seq dur runtime idle mean stddev sum min max smac dmac soui doui saddr daddr proto sport dport stos dtos sdsb ddsb sco dco sttl dttl shops dhops sipid dipid smpls dmpls autoid sas das ias cause nstroke snstroke dnstroke pkts spkts dpkts bytes sbytes dbytes appbytes sappbytes dappbytes pcr load sload dload loss sloss dloss ploss psloss pdloss retrans sretrans dretrans pretrans psretrans pdretrans sgap dgap rate srate drate dir sintpkt sintdist sintpktact sintdistact sintpktidl sintdistidl dintpkt dintdist dintpktact dintdistact dintpktidl dintdistidl sjit sjitact sjitidle djit djitact djitidle state label suser duser swin dwin svlan dvlan svid dvid svpri dvpri srng erng stcpb dtcpb tcprtt synack ackdat tcpopt inode offset smeansz dmeansz spktsz smaxsz dpktsz dmaxsz sminsz dminsz dminsz > $filename.csv
ra[822552]: 09:36:10.990158 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
../util/process_data_argus.sh: line 3: 822571 Segmentation fault      (core dumped) ra -r $filename.argus -c',' -s srcid rank stime ltime trans flgs seq dur runtime idle mean stddev sum min max smac dmac soui doui saddr daddr proto sport dport stos dtos sdsb ddsb sco dco sttl dttl shops dhops sipid dipid smpls dmpls autoid sas das ias cause nstroke snstroke dnstroke pkts spkts dpkts bytes sbytes dbytes appbytes sappbytes dappbytes pcr load sload dload loss sloss dloss ploss psloss pdloss retrans sretrans dretrans pretrans psretrans pdretrans sgap dgap rate srate drate dir sintpkt sintdist sintpktact sintdistact sintpktidl sintdistidl dintpkt dintdist dintpktact dintdistact dintpktidl dintdistidl sjit sjitact sjitidle djit djitact djitidle state label suser duser swin dwin svlan dvlan svid dvid svpri dvpri srng erng stcpb dtcpb tcprtt synack ackdat tcpopt inode offset smeansz dmeansz spktsz smaxsz dpktsz dmaxsz sminsz dminsz dminsz > $filename.csv
ra[822582]: 09:36:16.105937 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822588]: 09:36:17.116238 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822594]: 09:36:18.129602 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822606]: 09:36:19.140021 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822634]: 09:36:20.152680 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822640]: 09:36:21.164354 ArgusGenerateRecordStruct: pre ARGUS_DATA_DSR len is zero
ra[822646]: 09:36:22.172815 ArgusGenerateRecordStruct: post ARGUS_DATA_DSR len is zero
mkdir: cannot create directory ‘data/argus’: File exists
mkdir: cannot create directory ‘data/argus/csv’: File exists

In [3]:
# PCAP to CSV
!../util/pcap_to_csv.sh

mkdir: cannot create directory ‘data/csv’: File exists

In [4]:
# PCAPNG to CSV
!../util/pcapng_to_csv.sh

mkdir: cannot create directory ‘data/csv’: File exists

In [5]:
from os import listdir
from os.path import isfile, join

def getFilenames(path):
    return [path+f for f in listdir(path) if isfile(join(path, f))]

In [6]:
# Get argus data
arguspath = "data/argus/csv/"
argusCSVs = getFilenames(arguspath)

# Get pcap data
pcappath = "data/csv/"
pcapCSVs = getFilenames(pcappath)
data = argusCSVs + pcapCSVs

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv (pcapCSVs[0])
df

,frame.number,frame.time,ip.src,ip.dst,ip.proto,frame.len
0,1,"Dec 31, 1969 19:00:05.000000000 EST",195.201.29.252,100.0.0.1,6,40
1,2,"Dec 31, 1969 19:00:05.000000000 EST",195.201.29.252,100.0.0.3,6,40
2,3,"Dec 31, 1969 19:00:05.000000000 EST",195.201.29.252,100.0.0.1,6,40
3,4,"Dec 31, 1969 19:00:05.000000000 EST",195.201.29.252,100.0.0.2,6,40
4,5,"Dec 31, 1969 19:00:05.000000000 EST",195.201.29.252,100.0.0.3,6,40
...,...,...,...,...,...,...
12031,12032,"Dec 31, 1969 20:00:00.000000000 EST",195.201.29.252,100.0.0.2,6,40
12032,12033,"Dec 31, 1969 20:00:00.000000000 EST",195.201.29.252,192.42.116.13,6,40
12033,12034,"Dec 31, 1969 20:00:00.000000000 EST",195.201.29.252,209.141.45.173,6,40
12034,12035,"Dec 31, 1969 20:00:00.000000000 EST",195.201.29.252,100.0.0.1,6,40
12035,12036,"Dec 31, 1969 20:00:00.000000000 EST",195.201.29.252,192.42.116.13,6,40

In [9]:
data

['data/argus/csv/relay3guard-195.201.29.252.csv',
 'data/argus/csv/relay4middle-87.118.110.113.csv',
 'data/argus/csv/relay2exit-209.141.45.173.csv',
 'data/argus/csv/sld.csv',
 'data/argus/csv/4uthority1-127.0.0.1.csv',
 'data/argus/csv/server.csv',
 'data/argus/csv/relay3guard-127.0.0.1.csv',
 'data/argus/csv/relay1exitguard-127.0.0.1.csv',
 'data/argus/csv/4uthority1-100.0.0.1.csv',
 'data/argus/csv/4uthority2-127.0.0.1.csv',
 'data/argus/csv/relay3guard-198.98.54.105.csv',
 'data/argus/csv/root-server.csv',
 'data/argus/csv/relay1exitguard-192.42.116.19.csv',
 'data/argus/csv/myMarkovClient0-127.0.0.1.csv',
 'data/argus/csv/relay4middle-136.244.81.197.csv',
 'data/argus/csv/4uthority3-100.0.0.3.csv',
 'data/argus/csv/myMarkovServer0-101.0.0.10.csv',
 'data/argus/csv/relay2exit-198.98.53.153.csv',
 'data/argus/csv/4uthority2-100.0.0.2.csv',
 'data/argus/csv/client-to-isp.csv',
 'data/argus/csv/4uthority3-127.0.0.1.csv',
 'data/argus/csv/relay4middle-127.0.0.1.csv',
 'data/argus/csv/tld.csv',
 'data/argus/csv/myMarkovClient0-102.0.0.10.csv',
 'data/argus/csv/relay1exitguard-192.42.116.13.csv',
 'data/argus/csv/myMarkovServer0-127.0.0.1.csv',
 'data/argus/csv/lo-resolver.csv',
 'data/argus/csv/relay2exit-127.0.0.1.csv',
 'data/csv/relay3guard-195.201.29.252.csv',
 'data/csv/relay4middle-87.118.110.113.csv',
 'data/csv/relay2exit-209.141.45.173.csv',
 'data/csv/sld.csv',
 'data/csv/4uthority1-127.0.0.1.csv',
 'data/csv/server.csv',
 'data/csv/relay3guard-127.0.0.1.csv',
 'data/csv/relay1exitguard-127.0.0.1.csv',
 'data/csv/4uthority1-100.0.0.1.csv',
 'data/csv/4uthority2-127.0.0.1.csv',
 'data/csv/relay3guard-198.98.54.105.csv',
 'data/csv/root-server.csv',
 'data/csv/relay1exitguard-192.42.116.19.csv',
 'data/csv/myMarkovClient0-127.0.0.1.csv',
 'data/csv/relay4middle-136.244.81.197.csv',
 'data/csv/4uthority3-100.0.0.3.csv',
 'data/csv/myMarkovServer0-101.0.0.10.csv',
 'data/csv/relay2exit-198.98.53.153.csv',
 'data/csv/4uthority2-100.0.0.2.csv',
 'data/csv/client-to-isp.csv',
 'data/csv/4uthority3-127.0.0.1.csv',
 'data/csv/relay4middle-127.0.0.1.csv',
 'data/csv/tld.csv',
 'data/csv/myMarkovClient0-102.0.0.10.csv',
 'data/csv/relay1exitguard-192.42.116.13.csv',
 'data/csv/myMarkovServer0-127.0.0.1.csv',
 'data/csv/lo-resolver.csv',
 'data/csv/relay2exit-127.0.0.1.csv']

In [10]:
argusCSVs

['data/argus/csv/relay3guard-195.201.29.252.csv',
 'data/argus/csv/relay4middle-87.118.110.113.csv',
 'data/argus/csv/relay2exit-209.141.45.173.csv',
 'data/argus/csv/sld.csv',
 'data/argus/csv/4uthority1-127.0.0.1.csv',
 'data/argus/csv/server.csv',
 'data/argus/csv/relay3guard-127.0.0.1.csv',
 'data/argus/csv/relay1exitguard-127.0.0.1.csv',
 'data/argus/csv/4uthority1-100.0.0.1.csv',
 'data/argus/csv/4uthority2-127.0.0.1.csv',
 'data/argus/csv/relay3guard-198.98.54.105.csv',
 'data/argus/csv/root-server.csv',
 'data/argus/csv/relay1exitguard-192.42.116.19.csv',
 'data/argus/csv/myMarkovClient0-127.0.0.1.csv',
 'data/argus/csv/relay4middle-136.244.81.197.csv',
 'data/argus/csv/4uthority3-100.0.0.3.csv',
 'data/argus/csv/myMarkovServer0-101.0.0.10.csv',
 'data/argus/csv/relay2exit-198.98.53.153.csv',
 'data/argus/csv/4uthority2-100.0.0.2.csv',
 'data/argus/csv/client-to-isp.csv',
 'data/argus/csv/4uthority3-127.0.0.1.csv',
 'data/argus/csv/relay4middle-127.0.0.1.csv',
 'data/argus/csv/tld.csv',
 'data/argus/csv/myMarkovClient0-102.0.0.10.csv',
 'data/argus/csv/relay1exitguard-192.42.116.13.csv',
 'data/argus/csv/myMarkovServer0-127.0.0.1.csv',
 'data/argus/csv/lo-resolver.csv',
 'data/argus/csv/relay2exit-127.0.0.1.csv']

In [11]:
# Basic Scopes
import re

# Get all clients and ISP dns scope
r = re.compile(".*isp.csv|.*Client[0-9]*-(?!127\.0\.0\.1)[0-9]*.[0-9]*.[0-9]*.[0-9]*..csv")
ISP_scope = list(filter(r.match, data))

# Access to public resolver scope
r = re.compile(".*isp.csv")
Access_resolver = list(filter(r.match, data))

# DNS Scope
r = re.compile("(.*tld|.*root-server|.*sld).csv")
Access_to_auth_zone = list(filter(r.match, data))

# Access Tor Scope
r = re.compile(".*Client[0-9]*-(?!127\.0\.0\.1)[0-9]*.[0-9]*.[0-9]*.[0-9]*..csv")
Access_tor = list(filter(r.match, data))

# Server Public Scope
r = re.compile(".*myMarkovServer[0-9]*-(?!127\.0\.0\.1)[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*.csv")
Server_scope = list(filter(r.match, data))

# tor Exit scope
r = re.compile(".*exit.*")
Tor_exit_Scope = list(filter(r.match, data))

# tor Guard scope
r = re.compile(".*guard.*")
Tor_guard_Scope = list(filter(r.match, data))

# tor Relay scope
r = re.compile(".*relay.*")
Tor_relay_Scope = list(filter(r.match, data))

# tor Middle scope
r = re.compile(".*middle.*")
Tor_middle_Scope = list(filter(r.match, data))

# tor 4uthority scope
r = re.compile(".*4uthority.*")
Tor_4uthority_Scope = list(filter(r.match, data))

In [147]:
# !pip install pyts

from pyts.metrics import dtw, itakura_parallelogram, sakoe_chiba_band
from pyts.metrics.dtw import (cost_matrix, accumulated_cost_matrix,
                              _return_path, _blurred_path_region)

def compare_ts(ts1, ts2):
    dtw_classic, path_classic = dtw(ts1, ts2, dist='square',
                                method='classic', return_path=True)
    return dtw_classic

In [138]:
from pyts.datasets import load_gunpoint

X, _, _, _ = load_gunpoint(return_X_y=True)
x, y = X[0], X[1]

In [139]:
compare_ts(x, y)

0.43268499970930435

In [15]:
def get_ts(df, attr_list):
    return 1

In [16]:
def multi_to_single_tda(ts):
    return ts

In [105]:
def pcap_only(lis):
    r = re.compile(".*data/csv.*")
    return list(filter(r.match, lis))

def format_time_col(df, time_col):
    time_format='%b %d, %Y %X.%f'
    df[time_col] = df[time_col].apply(lambda x: datetime.strptime(x[:-7], time_format))
    df.set_index(time_col)
    return df

def scope_to_df(scope):
    df = pd.DataFrame()
    for f in scope:
        ddf = pd.read_csv (f)
        df = pd.concat([df, ddf])
    return df

In [110]:
# get start time for GNS3
GNS3_data = format_time_col(scope_to_df(pcap_only(Access_resolver + Access_to_auth_zone)), 'frame.time')
GNS3_starttime = GNS3_data.head(1)['frame.time'].tolist()[0]
Shadow_starttime = datetime.strptime('Dec 31, 1969 19:30:00', '%b %d, %Y %X')
Shadow_offset = GNS3_starttime - Shadow_starttime
Shadow_offset

Timedelta('19326 days 16:26:49.390748')

In [115]:
from datetime import datetime

def df_to_ts(df):
    df['count'] = 1
    return df.set_index('frame.time').resample('S').sum().dropna().reset_index()

In [116]:
dns_df = format_time_col(scope_to_df(pcap_only(Access_to_auth_zone)), 'frame.time')
# get Just DNS packets from capture
DNS_PROTO = 17.0
dns_df_filtered = dns_df[dns_df['ip.proto'] == DNS_PROTO]
# just get DNS requests
dns_df_filtered = dns_df_filtered[dns_df_filtered['ip.dst'] == "172.16.1.10"]

dns_ts = df_to_ts(dns_df_filtered)
dns_ts

           frame.time  frame.number  ip.proto  frame.len  count
0 2022-11-30 11:58:11           168     119.0        563      7

In [125]:
server_df = format_time_col(scope_to_df(pcap_only(Server_scope)), 'frame.time')

sus_ip = "192.42.116.13"

# Get sus Server posts
TCP_PROTO = 6.0
server_df = server_df[server_df['ip.proto'] == TCP_PROTO]
server_df = server_df[server_df['frame.len'] >47]
server_df['frame.time'] = server_df['frame.time'].apply(lambda x: x + Shadow_offset)

to_sus = server_df[server_df['ip.dst'] == sus_ip].copy()
from_sus = server_df[server_df['ip.src'] == sus_ip].copy()

to_sus_ts = df_to_ts(to_sus)

to_sus_ts

            frame.time  frame.number  ip.proto  frame.len  count
0  2022-11-30 11:56:49             5         6        152      1
1  2022-11-30 11:56:50            43        12        304      2
2  2022-11-30 11:56:51            38         6        152      1
3  2022-11-30 11:56:52           109        12        304      2
4  2022-11-30 11:56:53           153        12        304      2
5  2022-11-30 11:56:54           197        12        304      2
6  2022-11-30 11:56:55           115         6        152      1
7  2022-11-30 11:56:56           263        12        304      2
8  2022-11-30 11:56:57           307        12        304      2
9  2022-11-30 11:56:58           351        12        304      2
10 2022-11-30 11:56:59           192         6        152      1
11 2022-11-30 11:57:00           417        12        304      2

In [136]:
from_sus_ts = df_to_ts(from_sus)
from_sus_ts

            frame.time  frame.number  ip.proto  frame.len  count
0  2022-11-30 11:56:49             4         6        200      1
1  2022-11-30 11:56:50            41        12        401      2
2  2022-11-30 11:56:51            37         6        200      1
3  2022-11-30 11:56:52           107        12        401      2
4  2022-11-30 11:56:53           151        12        400      2
5  2022-11-30 11:56:54           195        12        400      2
6  2022-11-30 11:56:55           114         6        200      1
7  2022-11-30 11:56:56           261        12        401      2
8  2022-11-30 11:56:57           305        12        400      2
9  2022-11-30 11:56:58           349        12        401      2
10 2022-11-30 11:56:59           191         6        200      1
11 2022-11-30 11:57:00           415        12        400      2

In [148]:
compare_ts(to_sus_ts['count'], from_sus_ts['count'])

0.0

In [155]:
from datetime import timedelta
# get sus IPs
dns_ts_candidates = dns_ts[dns_ts['frame.time'] - from_sus_ts.head(1)['frame.time'] < timedelta(minutes=2)]
dns_ts_candidates

           frame.time  frame.number  ip.proto  frame.len  count
0 2022-11-30 11:58:11           168     119.0        563      7